# DIANA Setup for the RIH CIRR
# Merck, Winter 2018

# > ansible-playbook -i secrets/my_inventory.yml --vault-password secrets/vault_pw.txt cirr_playbook.yml -t indexer

---
##########################

# Setup the indexer first and add the Splunk HEC token to the inventory file so
# consolidated logging works for everything else.

- name: Setup CIRR Indexer
  tags: indexer
  hosts: indexer

  vars_files:
  - secrets/vault.yml
  - globals.yml

  # Required credentials for the script, include them separately in 'secrets.yml'
  vars:
    # CIFS mount vars
    smb_source_path:  "{{ vault_smb_source_path }}"
    smb_user:         "{{ vault_smb_user }}"
    smb_pw:           "{{ vault_smb_pw }}"

  roles:
#  - role:        cifs_client
#    mount_pt:    /mnt/hl7
#    source_path: "{{ smb_source_path }}"

  - role: splunk
    mount_pt: /mnt/hl7

##########################

- name: Setup CIRR Archive
  tags: archive
  hosts: archive

  vars_files:
  - secrets/vault.yml
  - globals.yml

  roles:
  - role:        orthanc
    title:       CIRR Archive
    db_name:     archive2
    c_name:      "orthanc_connect"
    api_port:    8142
    dicom_port:  4242
    admin_pw:    "{{ orthanc_admin_pw }}"

  tasks:
  - include_role:
      name: orthanc
    vars:
      title:     "CIRR Archive - Worker {{ item }}"
      db_name:   archive2
      c_name:    "orthanc_{{ item }}"
      # compress_dicom: true
      api_port:  "824{{ item }}"
      admin_pw:  "{{ orthanc_admin_pw }}"
    with_sequence: count=3

  - include_role:
      name: nginx
    vars:
      port: 8042
      conf_type: rest-head
      r_proxies:
      # links to container and native port, not docker bridge port
        orthanc_1:
          port: 8042
        orthanc_2:
          port: 8042
        orthanc_3:
          port: 8042


##########################

- name: Setup CIRR Router
  tags: router
  hosts: router

  vars_files:
  - secrets/vault.yml
  - globals.yml

  # TODO: Exec into compressor and install gcdm manually on rebuild
  # $ apt-get update
  # $ apt-get install libgdcm-tools
  roles:
  - role:    orthanc
    title:   CIRR Archive Router
    c_name:  orthanc_archive_in
    api_port:   8344  # Network b/u stuff running on 8343? nsrexecd
    dicom_port: 4243
    admin_pw:   "{{ orthanc_admin_pw }}"
    peers:
      archive:
        Url:      "http://{{ archive_ip }}:8042"
        Username: "orthanc"
        Password: "{{ orthanc_admin_pw }}"
    compress_dicom: True
    destinations:
    - type: peer
      dest: archive

  - role:    orthanc
    title:   CIRR Archive + Terarecon Router
    c_name:  orthanc_mux
    api_port:   8346
    dicom_port: 4246
    admin_pw:   "{{ orthanc_admin_pw }}"
    link_peers:  True
    peers:
      orthanc_archive_in:
        Url:      "http://orthanc_archive_in:8042"
        Username: "orthanc"
        Password: "{{ orthanc_admin_pw }}"
    destinations:
    - type: peer
      dest: orthanc-archive-in   # b/c no underscores
    - type: dicom
      dest: terarecon

#########################

- name: Setup CIRR Monitor
  tags: monitor
  hosts: indexer

  vars_files:
  - secrets/vault.yml
  - globals.yml

  roles:

  # TODO: Setup d-mon to identify and pull dose data...
  - role:        diana-monitor
    dmon_config: cirr_dmon_cfg.yml

    series_index:  dicom_series
    dose_index:    dose_reports
    dose_reports_query: "series_id==501 | series_id==900"

  # Add the dose monitoring app
  - role: splunk-dose

